### ISSUE TITLE
Publish version 1.0.0 on crates

### ISSUE THREAD

**Issue by fleupold** [synlestidae/ethereum-tx-sign#11]
https://github.com/synlestidae/ethereum-tx-sign/pull/3/files bumped the version to 1.0.0 introducing the critical functionality to manually set the CHAIN_ID for signing.

However, the latest version available on crates.io is 0.0.2 (https://github.com/synlestidae/ethereum-tx-sign)

Could we please push the most recent version to crates.io?

**Comment by synlestidae** [comment]
Done! Thanks for letting me know.
