### ISSUE TITLE
Use of types in RawTransaction struct

### ISSUE THREAD

**Issue by victor-wei126** [synlestidae/ethereum-tx-sign#24]
Curious why is U256 used for the fields of nonce, value, gasPrice, and gas? I haven't been able to find a specific reference to the exact type, the yellow paper just says use a scalar value. Geth uses big.Int. Could the primitive Rust type of u128 be used just as easily?

Similarly, the to field uses H160, from `ethereum-types` crate, why not use [u8; 20]? This leads to less dependencies and the user of the library doesn't need these crates.

**Comment by synlestidae** [comment]
I think it is a good idea to use Rust types where possible.
Years ago my intention for the library was to improve the tools in the web3/ethereum space with a way to sign transactions offline. Using U256 was an easy way to get the lib started.

I've started a branch `simplify-types` to look into changing the types, and removing ethereum-types as a dependency if possible. I'll have to confirm any data type changes with the eth yellow paper. Contributions on this branch are welcome.

**Comment by synlestidae** [comment]
Closed by #28

**Comment by victor-wei126** [comment]
Sorry was taking a week off and just saw this. That makes sense.

I tried looking into the yellow paper but it didn't define any specific value for a lot of transaction fields, like gas, gaslimit, nonce, etc. It only said use a scalar value. I just used u128 in my PR since it was the biggest. But Geth uses u64 for some things. So I assume it doesn't matter. Not sure tho.
