### ISSUE TITLE
Expand library to create other types of Ethereum transactions

### ISSUE THREAD

**Issue by victor-wei126** [synlestidae/ethereum-tx-sign#29]
With EIP-2718 any arbitrary types of transactions can be added. Currently there are 3 types of transactions, LegacyTxns, FeeMarketEIP1559Txn, and AccessListEIP2930Txn. We only support LegacyTxns right now.

We should be able to easily expand the library to support these other transactions. I'm thinking something like an enum type:
```
enum Transaction {
   LegacyTransaction,
   FeeMarket...,
   ....
}
```

Must of the methods currently in the impl block can probably be applied to all txn types, so we could make some trait, and derive it for all transaction types. This could be something to look to in the future.

**Comment by synlestidae** [comment]
Seems like a good idea to implement EIP-2718 @victor-wei126 

I will need to do some research to full understand the new transaction type.

With the Transaction as an enum, the library probably doesn't need to have a trait. If Transaction was a trait and LegactTxn, FeeMarket... etc. were its implementors, then that could work. I'll have to weigh up the best approach.

If you are interested in collaborating do let me know. I work full time so it may take a while to sort it out. Help is definitely welcome!

**Comment by victor-wei126** [comment]
Sounds good! I would definitely be interested in collaborating as time allows :)

I haven't taken too in-depth a look at EIP-2718 either, but I'll read more into it and perhaps take a stab at it soon. And that makes sense that we don't need a trait. I was just thinking all the methods for the transaction types _should_ be the same (I think), except for the `new()` method (since we would probably want to have a way to instantiate each txn type). But we would not necessarily need a trait for that.

**Comment by synlestidae** [comment]
Okay great. I have created some issues to track this. It looks like EIP-2718 defines a standard that reserves new transaction types. Therefore we can implement EIP-2718, then support the new transaction types that depend on 2718.

I have created a development branch to track in-progress work. Make any pull requests there.

**Comment by synlestidae** [comment]
Now tracked by #39 and #40.
