### ISSUE TITLE
What is the difference between rlp() and hash()?

### ISSUE THREAD

**Issue by victor-wei126** [synlestidae/ethereum-tx-sign#43]
Looking at the methods implemented for `LegacyTransaction` there is a rlp and hash method, hash() being one of the trait methods. It looks to me that rlp() does the rlp encoding of the raw transaction, appending the nonce, gasPrice, gasLimit, to, value, and data fields as rlp encoded values.

The hash() function also rlp encodes the chain-id, and then two values of 0x80, and appends this to the rlp value returned by the `rlp()` method. Just curious what this is doing? Where in the Ethereum docs does it specify we need to rlp encode and add this to the transaction structure? I was just under the impression that we encode the 6 data fields I listed above, and then hash that. I was not aware of this additional work.

**Comment by synlestidae** [comment]
Hashing and rlp-encoding are separate processes. `rlp()` returns the transaction data unsigned, and `hash()`  is of course a hash of this data. 

`hash()` functions according to [EIP-155](https://eips.ethereum.org/EIPS/eip-155). Check out this quote: _you SHOULD_ [when computing the hash] _hash nine rlp encoded elements (nonce, gasprice, startgas, to, value, data, chainid, 0, 0). If you do, then the v of the signature MUST be set to {0,1} + CHAIN_ID * 2 + 35_.

**Comment by victor-wei126** [comment]
In that case, shouldn't line 97 and 98 append byte 0x00, not 0x80? https://github.com/synlestidae/ethereum-tx-sign/blob/development/src/lib.rs#L97

**Comment by synlestidae** [comment]
The integer zero is encoded as `0x80`. See [the examples here](https://eth.wiki/fundamentals/rlp). 

The question here has me thinking I need more tests to back up the implementation.

**Comment by victor-wei126** [comment]
Looking at the examples, however, it says the empty string (null) is encoded as 0x80, and the integer 0 is 0x00. And the EIP-155 docs say we should rlp encode 0,0. But I did use the past version of this library in my own wallet application, and it seemed to be signing transactions just fine. That being said, I guess when txns are verified, it wouldn't make a difference since the signature would validate anyways I think.

Wdym you may need more tests to back up the implementation?

**Comment by synlestidae** [comment]
I think you have raised some good questions and while answering I checked the implementation and didn't feel confident that the existing test suite is sufficient. It's too small. I'll be adding some more tests in the coming weeks.
