### ISSUE TITLE
Change chain_id from u8 to u32

### ISSUE THREAD

**Issue by tritone11** [synlestidae/ethereum-tx-sign#7]
chain_id as u8 make this library unsuable for all chains with a chain_id higher than 255

For example, private chains with the default chain id (1337) or the Görli testnet (6284)

This should be set as a u32, as the Stureby testnet for Constantinople has a chain id of 314158 as specified in the [EIP155 implementation](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)

**Comment by synlestidae** [comment]
Thanks for bringing it to my attention. 

Is there a specified upper bound on the value of CHAIN_ID? In case u32 is not future proof

**Comment by tritone11** [comment]
@synlestidae as cited [here](https://ethereum.stackexchange.com/a/38657/50097), it is defined in geth as a BigInt, so the upper bound would be architecture dependent. It could be a u64 just to be sure

**Comment by reuvenpo** [comment]
I want to bump this as I'm trying to use this crate and I need to use these sorts of high chain ids, so I'm bumping this thread.

Also, according to [this yet-unmerged PR](https://github.com/tomusdrw/rust-web3/pull/279/) on `rust-web3` [it can be a u64](https://github.com/tomusdrw/rust-web3/pull/279/files#diff-f991d9f8cd3f37842355b9036fa2cc20R227).

**Comment by synlestidae** [comment]
This change should be straightforward. I've scheduled myself some time to get it released this weekend.

**Comment by reuvenpo** [comment]
Awesome! We really appreciate it! :)

**Comment by synlestidae** [comment]
Closing this issue thanks to @Cashmaney's changes in #15
